# Classification

In [ ]:
!pip install Xgboost

In [ ]:
from sklearn.datasets import make_classification


In [ ]:
X,y = make_classification(n_samples=1000,n_features=20,n_informative=15,n_redundant=0,random_state=0, shuffle=False)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=33,random_state=42)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
import xgboost as xb


In [ ]:
classifier1 = AdaBoostClassifier(n_estimators=100)

In [ ]:
classifier1.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
y_pred1=classifier1.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred1))

[[12  6]
 [ 4 11]]


In [ ]:
print(accuracy_score(y_test,y_pred1))

0.696969696969697


In [ ]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.75      0.67      0.71        18
           1       0.65      0.73      0.69        15

    accuracy                           0.70        33
   macro avg       0.70      0.70      0.70        33
weighted avg       0.70      0.70      0.70        33



In [ ]:
classifier2 = GradientBoostingClassifier()

In [ ]:
classifier2.fit(X_train,y_train)

GradientBoostingClassifier()

In [ ]:
y_pred2=classifier2.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,y_pred2))

[[16  2]
 [ 2 13]]


In [ ]:
print(accuracy_score(y_test,y_pred2))

0.8787878787878788


In [ ]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        18
           1       0.87      0.87      0.87        15

    accuracy                           0.88        33
   macro avg       0.88      0.88      0.88        33
weighted avg       0.88      0.88      0.88        33



In [ ]:
classifier3=xb.XGBClassifier()

In [ ]:
classifier3.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_pred3=classifier3.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,y_pred3))

[[15  3]
 [ 0 15]]


In [ ]:
print(accuracy_score(y_test,y_pred3))

0.9090909090909091


In [ ]:
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91        18
           1       0.83      1.00      0.91        15

    accuracy                           0.91        33
   macro avg       0.92      0.92      0.91        33
weighted avg       0.92      0.91      0.91        33



# Regression task

In [3]:
from sklearn.datasets import make_regression

In [5]:
X , y = make_regression(n_features=4, n_informative=2, random_state=0, shuffle=False)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
from sklearn.ensemble import AdaBoostRegressor

In [10]:
from sklearn.ensemble import GradientBoostingRegressor

In [11]:
import xgboost as xb

In [15]:
ada = AdaBoostRegressor(random_state=42)
gbr = GradientBoostingRegressor(random_state=42)
xgb = xb.XGBRegressor(random_state=42, n_estimators=100, learning_rate=0.1)


In [16]:
ada.fit(X_train, y_train)
gbr.fit(X_train, y_train)
xgb.fit(X_train, y_train)


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [17]:
y_pred_ada = ada.predict(X_test)
y_pred_gbr = gbr.predict(X_test)
y_pred_xgb = xgb.predict(X_test)


In [21]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred, model_name):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    print(f"{model_name} Metrics:")
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R-squared: {r2:.2f}")

In [23]:
evaluate_model(y_test, y_pred_ada, "AdaBoost")

AdaBoost Metrics:
MSE: 118.31
RMSE: 10.88
R-squared: 0.87


In [24]:
evaluate_model(y_test, y_pred_gbr, "GradientBoosting")

GradientBoosting Metrics:
MSE: 87.16
RMSE: 9.34
R-squared: 0.90


In [25]:
evaluate_model(y_test, y_pred_xgb, "XGBoost")

XGBoost Metrics:
MSE: 97.14
RMSE: 9.86
R-squared: 0.89


In [26]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5]
}

grid = GridSearchCV(xb.XGBRegressor(random_state=42), param_grid,
                    cv=3, scoring='r2', n_jobs=-1)
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)

Best Parameters: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


# FIND BEST SCORE

In [27]:
print("Best Score:", grid.best_score_)

Best Score: 0.9168824008242393
